### ISSUE TITLE
Rename "tractography_file_format" to "trx" 

### ISSUE THREAD

**Issue by arokem** [tee-ar-ex/trx-python#24]
Everywhere where the former is currently used.

**Comment by frheault** [comment]
About that, when this is changed we should make sure to organize the root correctly.
Should we delete the zarr folder? Should we put the C++ folder next to the Python folder (with submodule underneath) or should they be side-by-side in a folder call trx

root/trx/cpp and root/trx/python
OR
root/trx_cpp and root/trx_python

And where should be the data. Small decisions here and there. But I personally don't know what is clearer or best practices.

**Comment by skoudoro** [comment]
> Should we put the C++ folder next to the Python folder 

Talking about that, to reduce the maintenance load, I wonder if the C++ implementation should have a python binding.

Having these 2 implementations in parallel increases the risk of behavior difference. I think this is something to keep in mind.

**Comment by arokem** [comment]
I'm -1 to @skoudoro's suggestion in https://github.com/tee-ar-ex/trx/issues/24#issuecomment-1116448522 -- at least at this point - for two reasongs: 

1. It would require compiling the C++ code for a variety of different platforms, which constitutes a maintenance burden of its own.
2.  It would significantly raise the bar to development and maintenance. 

For now, I think that we should treat the Python implementation as the reference implementation and make sure that other implementations are compliant with this implementation. We can define a set of tests that any implementation needs to pass in order to be considered compliant. At some later point, we can also write down in more detail what the specification of the file format is so that any implementation can be checked against it.

**Comment by skoudoro** [comment]
ok, thank you for clarifying the strategy

**Comment by arokem** [comment]
Regarding the questions in https://github.com/tee-ar-ex/trx/issues/24#issuecomment-1116443990: 

> Should we delete the zarr folder? 

Sure. I think we can delete that for now. 

> Should we put the C++ folder next to the Python folder (with submodule underneath) or should they be side-by-side in a folder call trx
>
> root/trx/cpp and root/trx/python
> OR
> root/trx_cpp and root/trx_python
>
> And where should be the data? 

Maybe, now that we have a GitHub org set up, it would be best to have separate repos for Python/C++/Javascript/data??
