### ISSUE TITLE
Move test data to more stable location

### ISSUE THREAD

**Issue by arokem** [tee-ar-ex/trx-python#25]
Some test data is currently in google drive. We might want to upload that to a more stable location (e.g., figshare or zenodo).

**Comment by Lestropie** [comment]
For *MRtrix3* we place test data in their own git repositories and link them via git submodules.

- Test data are themselves under version control.
- Software versions contain explicit links to test data versions; software can evolve with no change to data, data can evolve with no change to software (other than updating the link), and changes that influence both software and data concurrently are explicitly lodged as such.
- One-liner to download the appropriate version of the relevant test data upon execution of a testing script.

Not sure if it's overkill for this application, and the submodule handling is rather clunky and error-prone if you're not a git pro, but it works for us, so figured I'd at least make the suggestion.

**Comment by francopestilli** [comment]
The current idea for the long term is the following:
- Host a project on brainlife.io with dwi and t1w data at different resolutions and spaces (RAS, LAS etc). 
- The tractography could be generated with MRTrix and/or DIPY
- We will have different errors examples for the file
- The full pipeline will be available to regenerate the TRX.

In the short term we will use a small dataset with DWI, T1w and a couple of TRX examples. 
@frheault @ValHayot @anibalsolon

**Comment by anibalsolon** [comment]
@francopestilli @soichih @frheault I've created a public project & publication here:

https://brainlife.io/project/6289982fd0697cf1eae8e88d/detail
https://brainlife.io/pub/628eb34bd0697cf1eaf2c56d

However, in order to download the data, the request needs to be authenticated. What would be a good solution for downloading this data in CI? To create a user in BL for the project?

**Comment by arokem** [comment]
I think a dedicated bl user would be best. You could potentially restrict
its permissions to just download this data.

We could use the repo secrets to authenticate from within the ci

**Comment by anibalsolon** [comment]
@arokem sounds good!
