### ISSUE TITLE
Where is numpy dependency?

### ISSUE THREAD

**Issue by skoudoro** [tee-ar-ex/trx-python#56]
Hi all, Hi @arokem, Hi @frheault, 

on `pyproject.toml` or `setup.py`, I do not see `numpy` as a dependency. Furthermore, I would like to know what is the numpy minimum version for this package. 

Also, I do not see it in the Github Action. I supposed, pytest choose whatever it needs for numpy.

It would be great to clarify this point for DIPY.

**Comment by arokem** [comment]
Seems to be resolved: https://github.com/tee-ar-ex/trx-python/blob/master/setup.cfg#L32
