### ISSUE TITLE
Online Meeting

### ISSUE THREAD

**Issue by skoudoro** [tee-ar-ex/trx-python#6]
Hi @frheault,

As you know, every other week, we have a DIPY online meeting.

I propose you to lead the next one to talk about the tractography file format. 
The next one is **December 2nd, noon EST / 6pm CET**.  

Let me know what you think and if you are interested then I will update the calendar and start to promote this online discussion to have as many diffusion actors as we can.

**Comment by frheault** [comment]
Hello, I would be happy to present the current 'results' of my attempt at creating a file format that please everyone and lead a discussion on what I would need to improve.

However it is important to mention that at the moment I am not sure if there is strong opinion for or against anything I have done.
So it would be important to clearly state that this is ongoing work that we want to fast-track and not that I want to impose this 'draft version' or even myself.

But yeah, I would be happy to initiate the discussion about 'how to go forward' from this initial attempt.

**Comment by skoudoro** [comment]
ok, great and I completely agree. Can you give me a simple title? I think you will have the right word for that.

Something like: "Summary of Tractography file format discussion and future direction proposition". Does not sound good but you get the idea. When you have a title, We will start to tweet, send to mailing list, etc... more people to discuss, better

**Comment by frheault** [comment]
What about ''TRX, a community file format: Where do you come and where do you go?''

**Comment by frheault** [comment]
@skoudoro so is it the date decided? Should I start planing it on my end?

**Comment by skoudoro** [comment]
Yes, Let me update DIPY online meeting: December 2nd, noon EST / 6pm CET

**Comment by skoudoro** [comment]
Are you ok if we communicate it on Neurostart and nueroimaging mailing list?  

I let you add it on the Nibabel issue

**Comment by frheault** [comment]
I will try to frame the meeting so it doesn't turn into an incoherent free for all of suggestions, demands and weird questions but yeah you can invite people using the normal ways.

But I will orient the meeting toward power users and developers only. Just so it stay on topic.

**Comment by skoudoro** [comment]
ok, make sense. Sounds like a plan! I will start to promote to devs
