### ISSUE TITLE
TRX conda package needed : Last release of DIPY cannot provide conda package because of TRX dependency

### ISSUE THREAD

**Issue by skoudoro** [tee-ar-ex/trx-python#74]
Hi TRX team,

Currently, we are stuck in DIPY to provides Anaconda package because we depend on TRX. 

Not sure if there is an alternative but for now, we need a conda package for TRX to be able to provide DIPY conda package.

Can someone look at this ?

**Comment by skoudoro** [comment]
see : https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=845640&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=6d4b912b-175d-51da-0fd9-4d30fe1eb4e7&l=87 for reference

**Comment by arokem** [comment]
I can take a look but it will take a few days. Do you understand why it
doesn’t use the pypi package?

**Comment by skoudoro** [comment]
For now, no, I am starting to investigate. 

Thanks !

**Comment by skoudoro** [comment]
Hi @arokem,

What is the status of this? Did you start the process?

I checked of using Pipy package and it is highly NOT recommanded and hard to do it.

**Comment by arokem** [comment]
I have not done anything yet. What's the next step? Set up a conda forge package for trx-python?

**Comment by skoudoro** [comment]
> I have not done anything yet. What's the next step? Set up a conda forge package for trx-python?

yes !

**Comment by arokem** [comment]
OK! Just put this up, https://github.com/conda-forge/staged-recipes/pull/24890, so I hope we can have this ready before too long.

**Comment by arokem** [comment]
I believe this is completed. Closing.

**Comment by skoudoro** [comment]
Great! Thank you for this @arokem, I will look at the DIPY one tomorrow.

Thanks again!
